#!/bin/sh

rm out.txt &
gnome-terminal -e "python3 receiver.py 7007 7008 7003 out.txt" --window-with-profile=holder
sleep 0.1
gnome-terminal -e "python3 channel2.py 7001 7002 7003 7004 7005 7007 0.0" --window-with-profile=holder
sleep 0.1
gnome-terminal -e "python3 sender.py 7005 7006 7001 in.txt" --window-with-profile=holder
wait
