#!/bin/sh

rm out.txt &
gnome-terminal -e "python3 receiver.py" --window-with-profile=holder
sleep 0.1
gnome-terminal -e "python3 channel.py" --window-with-profile=holder
sleep 0.1
gnome-terminal -e "python3 sender.py" --window-with-profile=holder
wait
